<?php

use Illuminate\Database\Seeder;

class MunicipalityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('municipalities')->insert([ 'id' => 1, 'state_id' => 1, 'municipality' => 'Alto Orinoco' ]);
		DB::table('municipalities')->insert([ 'id' => 2, 'state_id' => 1, 'municipality' => 'Atabapo' ]);
		DB::table('municipalities')->insert([ 'id' => 3, 'state_id' => 1, 'municipality' => 'Atures' ]);
		DB::table('municipalities')->insert([ 'id' => 4, 'state_id' => 1, 'municipality' => 'Autana' ]);
		DB::table('municipalities')->insert([ 'id' => 5, 'state_id' => 1, 'municipality' => 'Manapiare' ]);
		DB::table('municipalities')->insert([ 'id' => 6, 'state_id' => 1, 'municipality' => 'Maroa' ]);
		DB::table('municipalities')->insert([ 'id' => 7, 'state_id' => 1, 'municipality' => 'Río Negro' ]);
		DB::table('municipalities')->insert([ 'id' => 8, 'state_id' => 2, 'municipality' => 'Anaco' ]);
		DB::table('municipalities')->insert([ 'id' => 9, 'state_id' => 2, 'municipality' => 'Aragua' ]);
		DB::table('municipalities')->insert([ 'id' => 10, 'state_id' => 2, 'municipality' => 'Manuel Ezequiel Bruzual' ]);
		DB::table('municipalities')->insert([ 'id' => 11, 'state_id' => 2, 'municipality' => 'Diego Bautista Urbaneja' ]);
		DB::table('municipalities')->insert([ 'id' => 12, 'state_id' => 2, 'municipality' => 'Fernando Peñalver' ]);
		DB::table('municipalities')->insert([ 'id' => 13, 'state_id' => 2, 'municipality' => 'Francisco Del Carmen Carvajal' ]);
		DB::table('municipalities')->insert([ 'id' => 14, 'state_id' => 2, 'municipality' => 'General Sir Arthur McGregor' ]);
		DB::table('municipalities')->insert([ 'id' => 15, 'state_id' => 2, 'municipality' => 'Guanta' ]);
		DB::table('municipalities')->insert([ 'id' => 16, 'state_id' => 2, 'municipality' => 'Independencia' ]);
		DB::table('municipalities')->insert([ 'id' => 17, 'state_id' => 2, 'municipality' => 'José Gregorio Monagas' ]);
		DB::table('municipalities')->insert([ 'id' => 18, 'state_id' => 2, 'municipality' => 'Juan Antonio Sotillo' ]);
		DB::table('municipalities')->insert([ 'id' => 19, 'state_id' => 2, 'municipality' => 'Juan Manuel Cajigal' ]);
		DB::table('municipalities')->insert([ 'id' => 20, 'state_id' => 2, 'municipality' => 'Libertad' ]);
		DB::table('municipalities')->insert([ 'id' => 21, 'state_id' => 2, 'municipality' => 'Francisco de Miranda' ]);
		DB::table('municipalities')->insert([ 'id' => 22, 'state_id' => 2, 'municipality' => 'Pedro María Freites' ]);
		DB::table('municipalities')->insert([ 'id' => 23, 'state_id' => 2, 'municipality' => 'Píritu' ]);
		DB::table('municipalities')->insert([ 'id' => 24, 'state_id' => 2, 'municipality' => 'San José de Guanipa' ]);
		DB::table('municipalities')->insert([ 'id' => 25, 'state_id' => 2, 'municipality' => 'San Juan de Capistrano' ]);
		DB::table('municipalities')->insert([ 'id' => 26, 'state_id' => 2, 'municipality' => 'Santa Ana' ]);
		DB::table('municipalities')->insert([ 'id' => 27, 'state_id' => 2, 'municipality' => 'Simón Bolívar' ]);
		DB::table('municipalities')->insert([ 'id' => 28, 'state_id' => 2, 'municipality' => 'Simón Rodríguez' ]);
		DB::table('municipalities')->insert([ 'id' => 29, 'state_id' => 3, 'municipality' => 'Achaguas' ]);
		DB::table('municipalities')->insert([ 'id' => 30, 'state_id' => 3, 'municipality' => 'Biruaca' ]);
		DB::table('municipalities')->insert([ 'id' => 31, 'state_id' => 3, 'municipality' => 'Muñóz' ]);
		DB::table('municipalities')->insert([ 'id' => 32, 'state_id' => 3, 'municipality' => 'Páez' ]);
		DB::table('municipalities')->insert([ 'id' => 33, 'state_id' => 3, 'municipality' => 'Pedro Camejo' ]);
		DB::table('municipalities')->insert([ 'id' => 34, 'state_id' => 3, 'municipality' => 'Rómulo Gallegos' ]);
		DB::table('municipalities')->insert([ 'id' => 35, 'state_id' => 3, 'municipality' => 'San Fernando' ]);
		DB::table('municipalities')->insert([ 'id' => 36, 'state_id' => 4, 'municipality' => 'Atanasio Girardot' ]);
		DB::table('municipalities')->insert([ 'id' => 37, 'state_id' => 4, 'municipality' => 'Bolívar' ]);
		DB::table('municipalities')->insert([ 'id' => 38, 'state_id' => 4, 'municipality' => 'Camatagua' ]);
		DB::table('municipalities')->insert([ 'id' => 39, 'state_id' => 4, 'municipality' => 'Francisco Linares Alcántara' ]);
		DB::table('municipalities')->insert([ 'id' => 40, 'state_id' => 4, 'municipality' => 'José Ángel Lamas' ]);
		DB::table('municipalities')->insert([ 'id' => 41, 'state_id' => 4, 'municipality' => 'José Félix Ribas' ]);
		DB::table('municipalities')->insert([ 'id' => 42, 'state_id' => 4, 'municipality' => 'José Rafael Revenga' ]);
		DB::table('municipalities')->insert([ 'id' => 43, 'state_id' => 4, 'municipality' => 'Libertador' ]);
		DB::table('municipalities')->insert([ 'id' => 44, 'state_id' => 4, 'municipality' => 'Mario Briceño Iragorry' ]);
		DB::table('municipalities')->insert([ 'id' => 45, 'state_id' => 4, 'municipality' => 'Ocumare de la Costa de Oro' ]);
		DB::table('municipalities')->insert([ 'id' => 46, 'state_id' => 4, 'municipality' => 'San Casimiro' ]);
		DB::table('municipalities')->insert([ 'id' => 47, 'state_id' => 4, 'municipality' => 'San Sebastián' ]);
		DB::table('municipalities')->insert([ 'id' => 48, 'state_id' => 4, 'municipality' => 'Santiago Mariño' ]);
		DB::table('municipalities')->insert([ 'id' => 49, 'state_id' => 4, 'municipality' => 'Santos Michelena' ]);
		DB::table('municipalities')->insert([ 'id' => 50, 'state_id' => 4, 'municipality' => 'Sucre' ]);
		DB::table('municipalities')->insert([ 'id' => 51, 'state_id' => 4, 'municipality' => 'Tovar' ]);
		DB::table('municipalities')->insert([ 'id' => 52, 'state_id' => 4, 'municipality' => 'Urdaneta' ]);
		DB::table('municipalities')->insert([ 'id' => 53, 'state_id' => 4, 'municipality' => 'Zamora' ]);
		DB::table('municipalities')->insert([ 'id' => 54, 'state_id' => 5, 'municipality' => 'Alberto Arvelo Torrealba' ]);
		DB::table('municipalities')->insert([ 'id' => 55, 'state_id' => 5, 'municipality' => 'Andrés Eloy Blanco' ]);
		DB::table('municipalities')->insert([ 'id' => 56, 'state_id' => 5, 'municipality' => 'Antonio José de Sucre' ]);
		DB::table('municipalities')->insert([ 'id' => 57, 'state_id' => 5, 'municipality' => 'Arismendi' ]);
		DB::table('municipalities')->insert([ 'id' => 58, 'state_id' => 5, 'municipality' => 'Barinas' ]);
		DB::table('municipalities')->insert([ 'id' => 59, 'state_id' => 5, 'municipality' => 'Bolívar' ]);
		DB::table('municipalities')->insert([ 'id' => 60, 'state_id' => 5, 'municipality' => 'Cruz Paredes' ]);
		DB::table('municipalities')->insert([ 'id' => 61, 'state_id' => 5, 'municipality' => 'Ezequiel Zamora' ]);
		DB::table('municipalities')->insert([ 'id' => 62, 'state_id' => 5, 'municipality' => 'Obispos' ]);
		DB::table('municipalities')->insert([ 'id' => 63, 'state_id' => 5, 'municipality' => 'Pedraza' ]);
		DB::table('municipalities')->insert([ 'id' => 64, 'state_id' => 5, 'municipality' => 'Rojas' ]);
		DB::table('municipalities')->insert([ 'id' => 65, 'state_id' => 5, 'municipality' => 'Sosa' ]);
		DB::table('municipalities')->insert([ 'id' => 66, 'state_id' => 6, 'municipality' => 'Caroní' ]);
		DB::table('municipalities')->insert([ 'id' => 67, 'state_id' => 6, 'municipality' => 'Cedeño' ]);
		DB::table('municipalities')->insert([ 'id' => 68, 'state_id' => 6, 'municipality' => 'El Callao' ]);
		DB::table('municipalities')->insert([ 'id' => 69, 'state_id' => 6, 'municipality' => 'Gran Sabana' ]);
		DB::table('municipalities')->insert([ 'id' => 70, 'state_id' => 6, 'municipality' => 'Heres' ]);
		DB::table('municipalities')->insert([ 'id' => 71, 'state_id' => 6, 'municipality' => 'Piar' ]);
		DB::table('municipalities')->insert([ 'id' => 72, 'state_id' => 6, 'municipality' => 'Angostura (Raúl Leoni)' ]);
		DB::table('municipalities')->insert([ 'id' => 73, 'state_id' => 6, 'municipality' => 'Roscio' ]);
		DB::table('municipalities')->insert([ 'id' => 74, 'state_id' => 6, 'municipality' => 'Sifontes' ]);
		DB::table('municipalities')->insert([ 'id' => 75, 'state_id' => 6, 'municipality' => 'Sucre' ]);
		DB::table('municipalities')->insert([ 'id' => 76, 'state_id' => 6, 'municipality' => 'Padre Pedro Chien' ]);
		DB::table('municipalities')->insert([ 'id' => 77, 'state_id' => 7, 'municipality' => 'Bejuma' ]);
		DB::table('municipalities')->insert([ 'id' => 78, 'state_id' => 7, 'municipality' => 'Carlos Arvelo' ]);
		DB::table('municipalities')->insert([ 'id' => 79, 'state_id' => 7, 'municipality' => 'Diego Ibarra' ]);
		DB::table('municipalities')->insert([ 'id' => 80, 'state_id' => 7, 'municipality' => 'Guacara' ]);
		DB::table('municipalities')->insert([ 'id' => 81, 'state_id' => 7, 'municipality' => 'Juan José Mora' ]);
		DB::table('municipalities')->insert([ 'id' => 82, 'state_id' => 7, 'municipality' => 'Libertador' ]);
		DB::table('municipalities')->insert([ 'id' => 83, 'state_id' => 7, 'municipality' => 'Los Guayos' ]);
		DB::table('municipalities')->insert([ 'id' => 84, 'state_id' => 7, 'municipality' => 'Miranda' ]);
		DB::table('municipalities')->insert([ 'id' => 85, 'state_id' => 7, 'municipality' => 'Montalbán' ]);
		DB::table('municipalities')->insert([ 'id' => 86, 'state_id' => 7, 'municipality' => 'Naguanagua' ]);
		DB::table('municipalities')->insert([ 'id' => 87, 'state_id' => 7, 'municipality' => 'Puerto Cabello' ]);
		DB::table('municipalities')->insert([ 'id' => 88, 'state_id' => 7, 'municipality' => 'San Diego' ]);
		DB::table('municipalities')->insert([ 'id' => 89, 'state_id' => 7, 'municipality' => 'San Joaquín' ]);
		DB::table('municipalities')->insert([ 'id' => 90, 'state_id' => 7, 'municipality' => 'Valencia' ]);
		DB::table('municipalities')->insert([ 'id' => 91, 'state_id' => 8, 'municipality' => 'Anzoátegui' ]);
		DB::table('municipalities')->insert([ 'id' => 92, 'state_id' => 8, 'municipality' => 'Tinaquillo' ]);
		DB::table('municipalities')->insert([ 'id' => 93, 'state_id' => 8, 'municipality' => 'Girardot' ]);
		DB::table('municipalities')->insert([ 'id' => 94, 'state_id' => 8, 'municipality' => 'Lima Blanco' ]);
		DB::table('municipalities')->insert([ 'id' => 95, 'state_id' => 8, 'municipality' => 'Pao de San Juan Bautista' ]);
		DB::table('municipalities')->insert([ 'id' => 96, 'state_id' => 8, 'municipality' => 'Ricaurte' ]);
		DB::table('municipalities')->insert([ 'id' => 97, 'state_id' => 8, 'municipality' => 'Rómulo Gallegos' ]);
		DB::table('municipalities')->insert([ 'id' => 98, 'state_id' => 8, 'municipality' => 'San Carlos' ]);
		DB::table('municipalities')->insert([ 'id' => 99, 'state_id' => 8, 'municipality' => 'Tinaco' ]);
		DB::table('municipalities')->insert([ 'id' => 100, 'state_id' => 9, 'municipality' => 'Antonio Díaz' ]);
		DB::table('municipalities')->insert([ 'id' => 101, 'state_id' => 9, 'municipality' => 'Casacoima' ]);
		DB::table('municipalities')->insert([ 'id' => 102, 'state_id' => 9, 'municipality' => 'Pedernales' ]);
		DB::table('municipalities')->insert([ 'id' => 103, 'state_id' => 9, 'municipality' => 'Tucupita' ]);
		DB::table('municipalities')->insert([ 'id' => 104, 'state_id' => 10, 'municipality' => 'Acosta' ]);
		DB::table('municipalities')->insert([ 'id' => 105, 'state_id' => 10, 'municipality' => 'Bolívar' ]);
		DB::table('municipalities')->insert([ 'id' => 106, 'state_id' => 10, 'municipality' => 'Buchivacoa' ]);
		DB::table('municipalities')->insert([ 'id' => 107, 'state_id' => 10, 'municipality' => 'Cacique Manaure' ]);
		DB::table('municipalities')->insert([ 'id' => 108, 'state_id' => 10, 'municipality' => 'Carirubana' ]);
		DB::table('municipalities')->insert([ 'id' => 109, 'state_id' => 10, 'municipality' => 'Colina' ]);
		DB::table('municipalities')->insert([ 'id' => 110, 'state_id' => 10, 'municipality' => 'Dabajuro' ]);
		DB::table('municipalities')->insert([ 'id' => 111, 'state_id' => 10, 'municipality' => 'Democracia' ]);
		DB::table('municipalities')->insert([ 'id' => 112, 'state_id' => 10, 'municipality' => 'Falcón' ]);
		DB::table('municipalities')->insert([ 'id' => 113, 'state_id' => 10, 'municipality' => 'Federación' ]);
		DB::table('municipalities')->insert([ 'id' => 114, 'state_id' => 10, 'municipality' => 'Jacura' ]);
		DB::table('municipalities')->insert([ 'id' => 115, 'state_id' => 10, 'municipality' => 'José Laurencio Silva' ]);
		DB::table('municipalities')->insert([ 'id' => 116, 'state_id' => 10, 'municipality' => 'Los Taques' ]);
		DB::table('municipalities')->insert([ 'id' => 117, 'state_id' => 10, 'municipality' => 'Mauroa' ]);
		DB::table('municipalities')->insert([ 'id' => 118, 'state_id' => 10, 'municipality' => 'Miranda' ]);
		DB::table('municipalities')->insert([ 'id' => 119, 'state_id' => 10, 'municipality' => 'Monseñor Iturriza' ]);
		DB::table('municipalities')->insert([ 'id' => 120, 'state_id' => 10, 'municipality' => 'Palmasola' ]);
		DB::table('municipalities')->insert([ 'id' => 121, 'state_id' => 10, 'municipality' => 'Petit' ]);
		DB::table('municipalities')->insert([ 'id' => 122, 'state_id' => 10, 'municipality' => 'Píritu' ]);
		DB::table('municipalities')->insert([ 'id' => 123, 'state_id' => 10, 'municipality' => 'San Francisco' ]);
		DB::table('municipalities')->insert([ 'id' => 124, 'state_id' => 10, 'municipality' => 'Sucre' ]);
		DB::table('municipalities')->insert([ 'id' => 125, 'state_id' => 10, 'municipality' => 'Tocópero' ]);
		DB::table('municipalities')->insert([ 'id' => 126, 'state_id' => 10, 'municipality' => 'Unión' ]);
		DB::table('municipalities')->insert([ 'id' => 127, 'state_id' => 10, 'municipality' => 'Urumaco' ]);
		DB::table('municipalities')->insert([ 'id' => 128, 'state_id' => 10, 'municipality' => 'Zamora' ]);
		DB::table('municipalities')->insert([ 'id' => 129, 'state_id' => 11, 'municipality' => 'Camaguán' ]);
		DB::table('municipalities')->insert([ 'id' => 130, 'state_id' => 11, 'municipality' => 'Chaguaramas' ]);
		DB::table('municipalities')->insert([ 'id' => 131, 'state_id' => 11, 'municipality' => 'El Socorro' ]);
		DB::table('municipalities')->insert([ 'id' => 132, 'state_id' => 11, 'municipality' => 'José Félix Ribas' ]);
		DB::table('municipalities')->insert([ 'id' => 133, 'state_id' => 11, 'municipality' => 'José Tadeo Monagas' ]);
		DB::table('municipalities')->insert([ 'id' => 134, 'state_id' => 11, 'municipality' => 'Juan Germán Roscio' ]);
		DB::table('municipalities')->insert([ 'id' => 135, 'state_id' => 11, 'municipality' => 'Julián Mellado' ]);
		DB::table('municipalities')->insert([ 'id' => 136, 'state_id' => 11, 'municipality' => 'Las Mercedes' ]);
		DB::table('municipalities')->insert([ 'id' => 137, 'state_id' => 11, 'municipality' => 'Leonardo Infante' ]);
		DB::table('municipalities')->insert([ 'id' => 138, 'state_id' => 11, 'municipality' => 'Pedro Zaraza' ]);
		DB::table('municipalities')->insert([ 'id' => 139, 'state_id' => 11, 'municipality' => 'Ortíz' ]);
		DB::table('municipalities')->insert([ 'id' => 140, 'state_id' => 11, 'municipality' => 'San Gerónimo de Guayabal' ]);
		DB::table('municipalities')->insert([ 'id' => 141, 'state_id' => 11, 'municipality' => 'San José de Guaribe' ]);
		DB::table('municipalities')->insert([ 'id' => 142, 'state_id' => 11, 'municipality' => 'Santa María de Ipire' ]);
		DB::table('municipalities')->insert([ 'id' => 143, 'state_id' => 11, 'municipality' => 'Sebastián Francisco de Miranda' ]);
		DB::table('municipalities')->insert([ 'id' => 144, 'state_id' => 12, 'municipality' => 'Andrés Eloy Blanco' ]);
		DB::table('municipalities')->insert([ 'id' => 145, 'state_id' => 12, 'municipality' => 'Crespo' ]);
		DB::table('municipalities')->insert([ 'id' => 146, 'state_id' => 12, 'municipality' => 'Iribarren' ]);
		DB::table('municipalities')->insert([ 'id' => 147, 'state_id' => 12, 'municipality' => 'Jiménez' ]);
		DB::table('municipalities')->insert([ 'id' => 148, 'state_id' => 12, 'municipality' => 'Morán' ]);
		DB::table('municipalities')->insert([ 'id' => 149, 'state_id' => 12, 'municipality' => 'Palavecino' ]);
		DB::table('municipalities')->insert([ 'id' => 150, 'state_id' => 12, 'municipality' => 'Simón Planas' ]);
		DB::table('municipalities')->insert([ 'id' => 151, 'state_id' => 12, 'municipality' => 'Torres' ]);
		DB::table('municipalities')->insert([ 'id' => 152, 'state_id' => 12, 'municipality' => 'Urdaneta' ]);
		DB::table('municipalities')->insert([ 'id' => 179, 'state_id' => 13, 'municipality' => 'Alberto Adriani' ]);
		DB::table('municipalities')->insert([ 'id' => 180, 'state_id' => 13, 'municipality' => 'Andrés Bello' ]);
		DB::table('municipalities')->insert([ 'id' => 181, 'state_id' => 13, 'municipality' => 'Antonio Pinto Salinas' ]);
		DB::table('municipalities')->insert([ 'id' => 182, 'state_id' => 13, 'municipality' => 'Aricagua' ]);
		DB::table('municipalities')->insert([ 'id' => 183, 'state_id' => 13, 'municipality' => 'Arzobispo Chacón' ]);
		DB::table('municipalities')->insert([ 'id' => 184, 'state_id' => 13, 'municipality' => 'Campo Elías' ]);
		DB::table('municipalities')->insert([ 'id' => 185, 'state_id' => 13, 'municipality' => 'Caracciolo Parra Olmedo' ]);
		DB::table('municipalities')->insert([ 'id' => 186, 'state_id' => 13, 'municipality' => 'Cardenal Quintero' ]);
		DB::table('municipalities')->insert([ 'id' => 187, 'state_id' => 13, 'municipality' => 'Guaraque' ]);
		DB::table('municipalities')->insert([ 'id' => 188, 'state_id' => 13, 'municipality' => 'Julio César Salas' ]);
		DB::table('municipalities')->insert([ 'id' => 189, 'state_id' => 13, 'municipality' => 'Justo Briceño' ]);
		DB::table('municipalities')->insert([ 'id' => 190, 'state_id' => 13, 'municipality' => 'Libertador' ]);
		DB::table('municipalities')->insert([ 'id' => 191, 'state_id' => 13, 'municipality' => 'Miranda' ]);
		DB::table('municipalities')->insert([ 'id' => 192, 'state_id' => 13, 'municipality' => 'Obispo Ramos de Lora' ]);
		DB::table('municipalities')->insert([ 'id' => 193, 'state_id' => 13, 'municipality' => 'Padre Noguera' ]);
		DB::table('municipalities')->insert([ 'id' => 194, 'state_id' => 13, 'municipality' => 'Pueblo Llano' ]);
		DB::table('municipalities')->insert([ 'id' => 195, 'state_id' => 13, 'municipality' => 'Rangel' ]);
		DB::table('municipalities')->insert([ 'id' => 196, 'state_id' => 13, 'municipality' => 'Rivas Dávila' ]);
		DB::table('municipalities')->insert([ 'id' => 197, 'state_id' => 13, 'municipality' => 'Santos Marquina' ]);
		DB::table('municipalities')->insert([ 'id' => 198, 'state_id' => 13, 'municipality' => 'Sucre' ]);
		DB::table('municipalities')->insert([ 'id' => 199, 'state_id' => 13, 'municipality' => 'Tovar' ]);
		DB::table('municipalities')->insert([ 'id' => 200, 'state_id' => 13, 'municipality' => 'Tulio Febres Cordero' ]);
		DB::table('municipalities')->insert([ 'id' => 201, 'state_id' => 13, 'municipality' => 'Zea' ]);
		DB::table('municipalities')->insert([ 'id' => 223, 'state_id' => 14, 'municipality' => 'Acevedo' ]);
		DB::table('municipalities')->insert([ 'id' => 224, 'state_id' => 14, 'municipality' => 'Andrés Bello' ]);
		DB::table('municipalities')->insert([ 'id' => 225, 'state_id' => 14, 'municipality' => 'Baruta' ]);
		DB::table('municipalities')->insert([ 'id' => 226, 'state_id' => 14, 'municipality' => 'Brión' ]);
		DB::table('municipalities')->insert([ 'id' => 227, 'state_id' => 14, 'municipality' => 'Buroz' ]);
		DB::table('municipalities')->insert([ 'id' => 228, 'state_id' => 14, 'municipality' => 'Carrizal' ]);
		DB::table('municipalities')->insert([ 'id' => 229, 'state_id' => 14, 'municipality' => 'Chacao' ]);
		DB::table('municipalities')->insert([ 'id' => 230, 'state_id' => 14, 'municipality' => 'Cristóbal Rojas' ]);
		DB::table('municipalities')->insert([ 'id' => 231, 'state_id' => 14, 'municipality' => 'El Hatillo' ]);
		DB::table('municipalities')->insert([ 'id' => 232, 'state_id' => 14, 'municipality' => 'Guaicaipuro' ]);
		DB::table('municipalities')->insert([ 'id' => 233, 'state_id' => 14, 'municipality' => 'Independencia' ]);
		DB::table('municipalities')->insert([ 'id' => 234, 'state_id' => 14, 'municipality' => 'Lander' ]);
		DB::table('municipalities')->insert([ 'id' => 235, 'state_id' => 14, 'municipality' => 'Los Salias' ]);
		DB::table('municipalities')->insert([ 'id' => 236, 'state_id' => 14, 'municipality' => 'Páez' ]);
		DB::table('municipalities')->insert([ 'id' => 237, 'state_id' => 14, 'municipality' => 'Paz Castillo' ]);
		DB::table('municipalities')->insert([ 'id' => 238, 'state_id' => 14, 'municipality' => 'Pedro Gual' ]);
		DB::table('municipalities')->insert([ 'id' => 239, 'state_id' => 14, 'municipality' => 'Plaza' ]);
		DB::table('municipalities')->insert([ 'id' => 240, 'state_id' => 14, 'municipality' => 'Simón Bolívar' ]);
		DB::table('municipalities')->insert([ 'id' => 241, 'state_id' => 14, 'municipality' => 'Sucre' ]);
		DB::table('municipalities')->insert([ 'id' => 242, 'state_id' => 14, 'municipality' => 'Urdaneta' ]);
		DB::table('municipalities')->insert([ 'id' => 243, 'state_id' => 14, 'municipality' => 'Zamora' ]);
		DB::table('municipalities')->insert([ 'id' => 258, 'state_id' => 15, 'municipality' => 'Acosta' ]);
		DB::table('municipalities')->insert([ 'id' => 259, 'state_id' => 15, 'municipality' => 'Aguasay' ]);
		DB::table('municipalities')->insert([ 'id' => 260, 'state_id' => 15, 'municipality' => 'Bolívar' ]);
		DB::table('municipalities')->insert([ 'id' => 261, 'state_id' => 15, 'municipality' => 'Caripe' ]);
		DB::table('municipalities')->insert([ 'id' => 262, 'state_id' => 15, 'municipality' => 'Cedeño' ]);
		DB::table('municipalities')->insert([ 'id' => 263, 'state_id' => 15, 'municipality' => 'Ezequiel Zamora' ]);
		DB::table('municipalities')->insert([ 'id' => 264, 'state_id' => 15, 'municipality' => 'Libertador' ]);
		DB::table('municipalities')->insert([ 'id' => 265, 'state_id' => 15, 'municipality' => 'Maturín' ]);
		DB::table('municipalities')->insert([ 'id' => 266, 'state_id' => 15, 'municipality' => 'Piar' ]);
		DB::table('municipalities')->insert([ 'id' => 267, 'state_id' => 15, 'municipality' => 'Punceres' ]);
		DB::table('municipalities')->insert([ 'id' => 268, 'state_id' => 15, 'municipality' => 'Santa Bárbara' ]);
		DB::table('municipalities')->insert([ 'id' => 269, 'state_id' => 15, 'municipality' => 'Sotillo' ]);
		DB::table('municipalities')->insert([ 'id' => 270, 'state_id' => 15, 'municipality' => 'Uracoa' ]);
		DB::table('municipalities')->insert([ 'id' => 271, 'state_id' => 16, 'municipality' => 'Antolín del Campo' ]);
		DB::table('municipalities')->insert([ 'id' => 272, 'state_id' => 16, 'municipality' => 'Arismendi' ]);
		DB::table('municipalities')->insert([ 'id' => 273, 'state_id' => 16, 'municipality' => 'García' ]);
		DB::table('municipalities')->insert([ 'id' => 274, 'state_id' => 16, 'municipality' => 'Gómez' ]);
		DB::table('municipalities')->insert([ 'id' => 275, 'state_id' => 16, 'municipality' => 'Maneiro' ]);
		DB::table('municipalities')->insert([ 'id' => 276, 'state_id' => 16, 'municipality' => 'Marcano' ]);
		DB::table('municipalities')->insert([ 'id' => 277, 'state_id' => 16, 'municipality' => 'Mariño' ]);
		DB::table('municipalities')->insert([ 'id' => 278, 'state_id' => 16, 'municipality' => 'Península de Macanao' ]);
		DB::table('municipalities')->insert([ 'id' => 279, 'state_id' => 16, 'municipality' => 'Tubores' ]);
		DB::table('municipalities')->insert([ 'id' => 280, 'state_id' => 16, 'municipality' => 'Villalba' ]);
		DB::table('municipalities')->insert([ 'id' => 281, 'state_id' => 16, 'municipality' => 'Díaz' ]);
		DB::table('municipalities')->insert([ 'id' => 282, 'state_id' => 17, 'municipality' => 'Agua Blanca' ]);
		DB::table('municipalities')->insert([ 'id' => 283, 'state_id' => 17, 'municipality' => 'Araure' ]);
		DB::table('municipalities')->insert([ 'id' => 284, 'state_id' => 17, 'municipality' => 'Esteller' ]);
		DB::table('municipalities')->insert([ 'id' => 285, 'state_id' => 17, 'municipality' => 'Guanare' ]);
		DB::table('municipalities')->insert([ 'id' => 286, 'state_id' => 17, 'municipality' => 'Guanarito' ]);
		DB::table('municipalities')->insert([ 'id' => 287, 'state_id' => 17, 'municipality' => 'Monseñor José Vicente de Unda' ]);
		DB::table('municipalities')->insert([ 'id' => 288, 'state_id' => 17, 'municipality' => 'Ospino' ]);
		DB::table('municipalities')->insert([ 'id' => 289, 'state_id' => 17, 'municipality' => 'Páez' ]);
		DB::table('municipalities')->insert([ 'id' => 290, 'state_id' => 17, 'municipality' => 'Papelón' ]);
		DB::table('municipalities')->insert([ 'id' => 291, 'state_id' => 17, 'municipality' => 'San Genaro de Boconoíto' ]);
		DB::table('municipalities')->insert([ 'id' => 292, 'state_id' => 17, 'municipality' => 'San Rafael de Onoto' ]);
		DB::table('municipalities')->insert([ 'id' => 293, 'state_id' => 17, 'municipality' => 'Santa Rosalía' ]);
		DB::table('municipalities')->insert([ 'id' => 294, 'state_id' => 17, 'municipality' => 'Sucre' ]);
		DB::table('municipalities')->insert([ 'id' => 295, 'state_id' => 17, 'municipality' => 'Turén' ]);
		DB::table('municipalities')->insert([ 'id' => 296, 'state_id' => 18, 'municipality' => 'Andrés Eloy Blanco' ]);
		DB::table('municipalities')->insert([ 'id' => 297, 'state_id' => 18, 'municipality' => 'Andrés Mata' ]);
		DB::table('municipalities')->insert([ 'id' => 298, 'state_id' => 18, 'municipality' => 'Arismendi' ]);
		DB::table('municipalities')->insert([ 'id' => 299, 'state_id' => 18, 'municipality' => 'Benítez' ]);
		DB::table('municipalities')->insert([ 'id' => 300, 'state_id' => 18, 'municipality' => 'Bermúdez' ]);
		DB::table('municipalities')->insert([ 'id' => 301, 'state_id' => 18, 'municipality' => 'Bolívar' ]);
		DB::table('municipalities')->insert([ 'id' => 302, 'state_id' => 18, 'municipality' => 'Cajigal' ]);
		DB::table('municipalities')->insert([ 'id' => 303, 'state_id' => 18, 'municipality' => 'Cruz Salmerón Acosta' ]);
		DB::table('municipalities')->insert([ 'id' => 304, 'state_id' => 18, 'municipality' => 'Libertador' ]);
		DB::table('municipalities')->insert([ 'id' => 305, 'state_id' => 18, 'municipality' => 'Mariño' ]);
		DB::table('municipalities')->insert([ 'id' => 306, 'state_id' => 18, 'municipality' => 'Mejía' ]);
		DB::table('municipalities')->insert([ 'id' => 307, 'state_id' => 18, 'municipality' => 'Montes' ]);
		DB::table('municipalities')->insert([ 'id' => 308, 'state_id' => 18, 'municipality' => 'Ribero' ]);
		DB::table('municipalities')->insert([ 'id' => 309, 'state_id' => 18, 'municipality' => 'Sucre' ]);
		DB::table('municipalities')->insert([ 'id' => 310, 'state_id' => 18, 'municipality' => 'Valdéz' ]);
		DB::table('municipalities')->insert([ 'id' => 341, 'state_id' => 19, 'municipality' => 'Andrés Bello' ]);
		DB::table('municipalities')->insert([ 'id' => 342, 'state_id' => 19, 'municipality' => 'Antonio Rómulo Costa' ]);
		DB::table('municipalities')->insert([ 'id' => 343, 'state_id' => 19, 'municipality' => 'Ayacucho' ]);
		DB::table('municipalities')->insert([ 'id' => 344, 'state_id' => 19, 'municipality' => 'Bolívar' ]);
		DB::table('municipalities')->insert([ 'id' => 345, 'state_id' => 19, 'municipality' => 'Cárdenas' ]);
		DB::table('municipalities')->insert([ 'id' => 346, 'state_id' => 19, 'municipality' => 'Córdoba' ]);
		DB::table('municipalities')->insert([ 'id' => 347, 'state_id' => 19, 'municipality' => 'Fernández Feo' ]);
		DB::table('municipalities')->insert([ 'id' => 348, 'state_id' => 19, 'municipality' => 'Francisco de Miranda' ]);
		DB::table('municipalities')->insert([ 'id' => 349, 'state_id' => 19, 'municipality' => 'García de Hevia' ]);
		DB::table('municipalities')->insert([ 'id' => 350, 'state_id' => 19, 'municipality' => 'Guásimos' ]);
		DB::table('municipalities')->insert([ 'id' => 351, 'state_id' => 19, 'municipality' => 'Independencia' ]);
		DB::table('municipalities')->insert([ 'id' => 352, 'state_id' => 19, 'municipality' => 'Jáuregui' ]);
		DB::table('municipalities')->insert([ 'id' => 353, 'state_id' => 19, 'municipality' => 'José María Vargas' ]);
		DB::table('municipalities')->insert([ 'id' => 354, 'state_id' => 19, 'municipality' => 'Junín' ]);
		DB::table('municipalities')->insert([ 'id' => 355, 'state_id' => 19, 'municipality' => 'Libertad' ]);
		DB::table('municipalities')->insert([ 'id' => 356, 'state_id' => 19, 'municipality' => 'Libertador' ]);
		DB::table('municipalities')->insert([ 'id' => 357, 'state_id' => 19, 'municipality' => 'Lobatera' ]);
		DB::table('municipalities')->insert([ 'id' => 358, 'state_id' => 19, 'municipality' => 'Michelena' ]);
		DB::table('municipalities')->insert([ 'id' => 359, 'state_id' => 19, 'municipality' => 'Panamericano' ]);
		DB::table('municipalities')->insert([ 'id' => 360, 'state_id' => 19, 'municipality' => 'Pedro María Ureña' ]);
		DB::table('municipalities')->insert([ 'id' => 361, 'state_id' => 19, 'municipality' => 'Rafael Urdaneta' ]);
		DB::table('municipalities')->insert([ 'id' => 362, 'state_id' => 19, 'municipality' => 'Samuel Darío Maldonado' ]);
		DB::table('municipalities')->insert([ 'id' => 363, 'state_id' => 19, 'municipality' => 'San Cristóbal' ]);
		DB::table('municipalities')->insert([ 'id' => 364, 'state_id' => 19, 'municipality' => 'Seboruco' ]);
		DB::table('municipalities')->insert([ 'id' => 365, 'state_id' => 19, 'municipality' => 'Simón Rodríguez' ]);
		DB::table('municipalities')->insert([ 'id' => 366, 'state_id' => 19, 'municipality' => 'Sucre' ]);
		DB::table('municipalities')->insert([ 'id' => 367, 'state_id' => 19, 'municipality' => 'Torbes' ]);
		DB::table('municipalities')->insert([ 'id' => 368, 'state_id' => 19, 'municipality' => 'Uribante' ]);
		DB::table('municipalities')->insert([ 'id' => 369, 'state_id' => 19, 'municipality' => 'San Judas Tadeo' ]);
		DB::table('municipalities')->insert([ 'id' => 370, 'state_id' => 20, 'municipality' => 'Andrés Bello' ]);
		DB::table('municipalities')->insert([ 'id' => 371, 'state_id' => 20, 'municipality' => 'Boconó' ]);
		DB::table('municipalities')->insert([ 'id' => 372, 'state_id' => 20, 'municipality' => 'Bolívar' ]);
		DB::table('municipalities')->insert([ 'id' => 373, 'state_id' => 20, 'municipality' => 'Candelaria' ]);
		DB::table('municipalities')->insert([ 'id' => 374, 'state_id' => 20, 'municipality' => 'Carache' ]);
		DB::table('municipalities')->insert([ 'id' => 375, 'state_id' => 20, 'municipality' => 'Escuque' ]);
		DB::table('municipalities')->insert([ 'id' => 376, 'state_id' => 20, 'municipality' => 'José Felipe Márquez Cañizalez' ]);
		DB::table('municipalities')->insert([ 'id' => 377, 'state_id' => 20, 'municipality' => 'Juan Vicente Campos Elías' ]);
		DB::table('municipalities')->insert([ 'id' => 378, 'state_id' => 20, 'municipality' => 'La Ceiba' ]);
		DB::table('municipalities')->insert([ 'id' => 379, 'state_id' => 20, 'municipality' => 'Miranda' ]);
		DB::table('municipalities')->insert([ 'id' => 380, 'state_id' => 20, 'municipality' => 'Monte Carmelo' ]);
		DB::table('municipalities')->insert([ 'id' => 381, 'state_id' => 20, 'municipality' => 'Motatán' ]);
		DB::table('municipalities')->insert([ 'id' => 382, 'state_id' => 20, 'municipality' => 'Pampán' ]);
		DB::table('municipalities')->insert([ 'id' => 383, 'state_id' => 20, 'municipality' => 'Pampanito' ]);
		DB::table('municipalities')->insert([ 'id' => 384, 'state_id' => 20, 'municipality' => 'Rafael Rangel' ]);
		DB::table('municipalities')->insert([ 'id' => 385, 'state_id' => 20, 'municipality' => 'San Rafael de Carvajal' ]);
		DB::table('municipalities')->insert([ 'id' => 386, 'state_id' => 20, 'municipality' => 'Sucre' ]);
		DB::table('municipalities')->insert([ 'id' => 387, 'state_id' => 20, 'municipality' => 'Trujillo' ]);
		DB::table('municipalities')->insert([ 'id' => 388, 'state_id' => 20, 'municipality' => 'Urdaneta' ]);
		DB::table('municipalities')->insert([ 'id' => 389, 'state_id' => 20, 'municipality' => 'Valera' ]);
		DB::table('municipalities')->insert([ 'id' => 390, 'state_id' => 21, 'municipality' => 'Vargas' ]);
		DB::table('municipalities')->insert([ 'id' => 391, 'state_id' => 22, 'municipality' => 'Arístides Bastidas' ]);
		DB::table('municipalities')->insert([ 'id' => 392, 'state_id' => 22, 'municipality' => 'Bolívar' ]);
		DB::table('municipalities')->insert([ 'id' => 407, 'state_id' => 22, 'municipality' => 'Bruzual' ]);
		DB::table('municipalities')->insert([ 'id' => 408, 'state_id' => 22, 'municipality' => 'Cocorote' ]);
		DB::table('municipalities')->insert([ 'id' => 409, 'state_id' => 22, 'municipality' => 'Independencia' ]);
		DB::table('municipalities')->insert([ 'id' => 410, 'state_id' => 22, 'municipality' => 'José Antonio Páez' ]);
		DB::table('municipalities')->insert([ 'id' => 411, 'state_id' => 22, 'municipality' => 'La Trinidad' ]);
		DB::table('municipalities')->insert([ 'id' => 412, 'state_id' => 22, 'municipality' => 'Manuel Monge' ]);
		DB::table('municipalities')->insert([ 'id' => 413, 'state_id' => 22, 'municipality' => 'Nirgua' ]);
		DB::table('municipalities')->insert([ 'id' => 414, 'state_id' => 22, 'municipality' => 'Peña' ]);
		DB::table('municipalities')->insert([ 'id' => 415, 'state_id' => 22, 'municipality' => 'San Felipe' ]);
		DB::table('municipalities')->insert([ 'id' => 416, 'state_id' => 22, 'municipality' => 'Sucre' ]);
		DB::table('municipalities')->insert([ 'id' => 417, 'state_id' => 22, 'municipality' => 'Urachiche' ]);
		DB::table('municipalities')->insert([ 'id' => 418, 'state_id' => 22, 'municipality' => 'José Joaquín Veroes' ]);
		DB::table('municipalities')->insert([ 'id' => 441, 'state_id' => 23, 'municipality' => 'Almirante Padilla' ]);
		DB::table('municipalities')->insert([ 'id' => 442, 'state_id' => 23, 'municipality' => 'Baralt' ]);
		DB::table('municipalities')->insert([ 'id' => 443, 'state_id' => 23, 'municipality' => 'Cabimas' ]);
		DB::table('municipalities')->insert([ 'id' => 444, 'state_id' => 23, 'municipality' => 'Catatumbo' ]);
		DB::table('municipalities')->insert([ 'id' => 445, 'state_id' => 23, 'municipality' => 'Colón' ]);
		DB::table('municipalities')->insert([ 'id' => 446, 'state_id' => 23, 'municipality' => 'Francisco Javier Pulgar' ]);
		DB::table('municipalities')->insert([ 'id' => 447, 'state_id' => 23, 'municipality' => 'Páez' ]);
		DB::table('municipalities')->insert([ 'id' => 448, 'state_id' => 23, 'municipality' => 'Jesús Enrique Losada' ]);
		DB::table('municipalities')->insert([ 'id' => 449, 'state_id' => 23, 'municipality' => 'Jesús María Semprún' ]);
		DB::table('municipalities')->insert([ 'id' => 450, 'state_id' => 23, 'municipality' => 'La Cañada de Urdaneta' ]);
		DB::table('municipalities')->insert([ 'id' => 451, 'state_id' => 23, 'municipality' => 'Lagunillas' ]);
		DB::table('municipalities')->insert([ 'id' => 452, 'state_id' => 23, 'municipality' => 'Machiques de Perijá' ]);
		DB::table('municipalities')->insert([ 'id' => 453, 'state_id' => 23, 'municipality' => 'Mara' ]);
		DB::table('municipalities')->insert([ 'id' => 454, 'state_id' => 23, 'municipality' => 'Maracaibo' ]);
		DB::table('municipalities')->insert([ 'id' => 455, 'state_id' => 23, 'municipality' => 'Miranda' ]);
		DB::table('municipalities')->insert([ 'id' => 456, 'state_id' => 23, 'municipality' => 'Rosario de Perijá' ]);
		DB::table('municipalities')->insert([ 'id' => 457, 'state_id' => 23, 'municipality' => 'San Francisco' ]);
		DB::table('municipalities')->insert([ 'id' => 458, 'state_id' => 23, 'municipality' => 'Santa Rita' ]);
		DB::table('municipalities')->insert([ 'id' => 459, 'state_id' => 23, 'municipality' => 'Simón Bolívar' ]);
		DB::table('municipalities')->insert([ 'id' => 460, 'state_id' => 23, 'municipality' => 'Sucre' ]);
		DB::table('municipalities')->insert([ 'id' => 461, 'state_id' => 23, 'municipality' => 'Valmore Rodríguez' ]);
		DB::table('municipalities')->insert([ 'id' => 462, 'state_id' => 24, 'municipality' => 'Libertador' ]);
    }
}
